### ISSUE TITLE
Linux version doesn't run

### ISSUE THREAD

**Issue by HackerLacker** [ZooLSmith/MIGI3#3]
Hey! I am using Arch Linux and the bspwm window manager and I am facing the problem that MIGI will not start under any circumstances. I moved migi_linux to the CS:GO folder, made the file executable, ran the "migi -i" command, which successfully installed MIGI. I try to launch through the browser and regular CS:GO, I try to launch through the "-game migi/csgo" option, a black screen appears for 15 seconds and the game closes, and it doesn't matter if I launched the game with addons or not, the same thing happens. Hope you can help me.
P.S. I asked a friend who uses the same thing as me to run MIGI and he has the same issue.

**Comment by ZooLSmith** [comment]
Hey, sorry, the current linux build is quite old, I'll need to give it another shot when I can, I've been focussing on the Windows build as it's where the majority of players use it.

It could be the gameinfo.txt however which requires fullpaths since the linux CS:GO build has a lot of issues related to relatives, but I'm not sure. Without any information about the hang / crash, I don't think I'll be able to help you sadly.. CS:GO on linux isn't something I've toyed a lot with.

**Comment by HackerLacker** [comment]
I was able to find the only log, and even he has no idea why CS: GO doesn't want to work.

**Comment by HackerLacker** [comment]
![image](https://user-images.githubusercontent.com/59232119/126916873-6061e3e3-9d15-4a59-b920-2824641c35e3.png)

**Comment by HackerLacker** [comment]
I also tried to start the game by specifying the -game parameter with the full path (/home/ ...) and still the same issue

**Comment by ZooLSmith** [comment]
It's likely I've forgot about gamebreaking issues that they've recently did, but as I said, I'll have to look at it again, the build is 6 months old, since then they've broke pakXX loading and other things, that could be related to it.

No promises but I'll have to look into it soon enough. But yeah from your experience it's clear that the tool doesn't work as intended on linux since CS:GO is simply unable to start the mod without even any addons.

**Comment by HackerLacker** [comment]
Thanks! I'll be waiting.

**Comment by uapv1903705** [comment]
Sorry, I don't have the time or setup to look into it as of now. The Linux community on CS:GO is very small and bigger core CS:GO issues are present and have yet to be fixed in this project. It doesn't help that modding support without having recourse to hacks is dying on CS:GO as we speak.

**Comment by ZooLSmith** [comment]
Sorry, I don't have the time or setup to look into it as of now. The Linux community on CS:GO is very small and bigger core CS:GO issues are present and have yet to be fixed in this project. It doesn't help that modding support without having recourse to hacks is dying on CS:GO as we speak.

This is something I do on my free time for the community, I just don't have the time to look into it now.

**Comment by Gotchfutchian** [comment]
Yeah i understand, its just with Linux growing quite fast, especially after the steam deck, it would be cool to see it. Maybe if find that i have enough free time I could develop a linux branch but we all know most of those types of projects turn out.
